### ISSUE TITLE
Publicer løsning til en ekstern web server f.eks. Azure.

### ISSUE THREAD

**Issue by dentych** [dentych/ITTWEB#70]
Find ud af, hvilken cloud service der skal bruges, og brug den. Det kan også være heroku kan hoste C# applikationer, det aner jeg ikke en dej om. Hvis det er muligt kan det være det er nemmere end at uploade lortet til Azure..

**Comment by dentych** [comment]
@David176 vi har besluttet at du skal lave det :smile: 

(fordi vi har stress over mokastisk stokellering)

**Comment by David176** [comment]
Okay I make
